# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 303493c388dda365ea0617b35e8aa5fefdc5254ea540eae1dc9a70031eeab2028b99475d5a8b1411c8652af81712cf9a06ee03acf6550b958c9a69d4e2e3c400

test:
  secret_key_base: 75bc59d9a2d2cf57ff110262982ce3935c44cfaa42c3fdd20c3d8f11f5d8da55d9743a338057de4a6c0b0f54f609f7e348728c07df2f945a54c5196758eb7ed6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
